const actionTypes = {
    SELECT_PERSON: 'SELECT_PERSON',
    FETCH_PEOPLE_STARTED: 'FETCH_PEOPLE_STARTED',
    FETCH_FILMS_STARTED: 'FETCH_FILMS_STARTED',
    FETCH_PEOPLE_SUCCEEDED: 'FETCH_PEOPLE_SUCCEEDED',
    FETCH_FILMS_SUCCEEDED: 'FETCH_FILMS_SUCCEEDED'
};

export default actionTypes;